%import common.WS
%ignore WS

number: /-?\d+(\./d{1,4})?/
variable: /\$[a-zA-Z]+/

line: let?

?let: "let" variable "=" vector     -> letvec
    | "let" variable "=" range      -> letran
    | "let" variable "=" repeat     -> letrep
    | "let" variable "=" expr       -> letexpr

vector: "[" (number ",")* number ("," number)* "]"
range: "range" "(" (number ",")? number (number ",")? ")"
repeat: "repeat" "(" vector count ")"

?unary_op: "-"  -> neg

?num_binary_op: "+"     -> add
              | "-"     -> sub
              | "*"     -> mul
              | "/"     -> div
              | "%"     -> mod
              | "^"     -> exp

?vec_binary_op: "+"     -> vadd
              | "-"     -> vsub
              | "*"     -> vdot
              | "X"     -> vcross

?logical_op: "<"    -> lt
           | "<="   -> le
           | ">"    -> gt
           | ">="   -> ge
           | "=="   -> eq
           | "!="   -> ne

?expr: "map" num_binary_op number expr  -> map
     | "filter" logical_op number expr  -> filter
     | "concat" expr expr               -> concat
     | unary_op expr                    -> unary
     | expr vec_binary_op expr          -> binary
     | expr logical_op expr             -> logical
     | "(" expr ")"
     | variable
